// <auto-generated />
using System;
using GraphTaskTrackerBackend.Infrastructure.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GraphTaskTrackerBackend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260422065046_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssignedUserNodes", b =>
                {
                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("NodeId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AssignedUserNodes");
                });

            modelBuilder.Entity("GraphTaskTrackerBackend.Domain.Entities.Edge", b =>
                {
                    b.Property<Guid>("FromNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToNodeId")
                        .HasColumnType("uuid");

                    b.Property<long>("Weight")
                        .HasColumnType("bigint");

                    b.HasKey("FromNodeId", "ToNodeId");

                    b.HasIndex("ToNodeId");

                    b.ToTable("Edges", (string)null);
                });

            modelBuilder.Entity("GraphTaskTrackerBackend.Domain.Entities.Graph", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Description");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Description"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Description"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("UserId");

                    b.ToTable("Graphs");
                });

            modelBuilder.Entity("GraphTaskTrackerBackend.Domain.Entities.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GraphId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GraphId");

                    b.ToTable("Nodes", (string)null);
                });

            modelBuilder.Entity("GraphTaskTrackerBackend.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_User_Name_Gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Name" }, "IX_User_Name_Gin"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Name" }, "IX_User_Name_Gin"), new[] { "gin_trgm_ops" });

                    b.HasIndex(new[] { "Name" }, "IX_User_Name_Unique")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AssignedUserNodes", b =>
                {
                    b.HasOne("GraphTaskTrackerBackend.Domain.Entities.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraphTaskTrackerBackend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GraphTaskTrackerBackend.Domain.Entities.Edge", b =>
                {
                    b.HasOne("GraphTaskTrackerBackend.Domain.Entities.Node", "FromNode")
                        .WithMany()
                        .HasForeignKey("FromNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraphTaskTrackerBackend.Domain.Entities.Node", "ToNode")
                        .WithMany()
                        .HasForeignKey("ToNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromNode");

                    b.Navigation("ToNode");
                });

            modelBuilder.Entity("GraphTaskTrackerBackend.Domain.Entities.Graph", b =>
                {
                    b.HasOne("GraphTaskTrackerBackend.Domain.Entities.User", "User")
                        .WithMany("Graphs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GraphTaskTrackerBackend.Domain.Entities.Node", b =>
                {
                    b.HasOne("GraphTaskTrackerBackend.Domain.Entities.User", "Author")
                        .WithMany("AuthorNodes")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraphTaskTrackerBackend.Domain.Entities.Graph", "Graph")
                        .WithMany("Nodes")
                        .HasForeignKey("GraphId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Graph");
                });

            modelBuilder.Entity("GraphTaskTrackerBackend.Domain.Entities.Graph", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("GraphTaskTrackerBackend.Domain.Entities.User", b =>
                {
                    b.Navigation("AuthorNodes");

                    b.Navigation("Graphs");
                });
#pragma warning restore 612, 618
        }
    }
}
